ingA11yLabel": "Seguir escribiendo para mí",
  "quickActionKeepWriting": "Sigue escribiendo esto",
  "quickActionAutoRewrite": "Reescritura automática",
  "quickActionVisualizeTable": "Visualizar como una tabla",
  "quickActionVisualizeList": "Visualizar como una lista",
  "quickActionRegenerate": "Regenerar",
  "reasonText": "Indíquenos el motivo para informar de este contenido",
  "referenceSnippetQuote": "\"{0}\"",
  "referenceSnippetEllipsesQuote": "\"{0}...\"",
  "regenerateA11yLabel": "Regenerar",
  "regenerateA11yLabel_titleCase": "Regenerar",
  "regenerateTooltip": "Regenerar",
  "regenerateTooltip_titleCase": "Regenerar",
  "removeAttachmentTooltip": "Quitar datos adjuntos",
  "repla